# Generated by Django 5.2.4 on 2025-07-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_alter_user_email_alter_user_nationalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.IntegerField(default=1274526015),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
