# Generated by Django 5.2.4 on 2025-07-16 11:26

import accounts_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0004_alter_user_birthdate_alter_user_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts_app.models.UserManager()),
            ],
        ),
    ]
