# Generated by Django 5.2.4 on 2025-07-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nationalid',
            field=models.CharField(blank=True, null=True),
        ),
    ]
