# Generated by Django 5.2.4 on 2025-07-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0006_alter_user_nationalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
