# Generated by Django 5.2.4 on 2025-07-15 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(choices=[('Food & Drinks', 'Food & Drinks'), ('Office Supplies', 'Office Supplies'), ('Business Services', 'Business Services'), ('Memberships & Rentals', 'Memberships & Rentals'), ('Workshops & Training', 'Workshops & Training'), ('Merchandise', 'Merchandise'), ('Opex', 'Opex')], db_index=True, max_length=100)),
                ('sub_category', models.CharField(choices=[('Snacks', 'Snacks'), ('Hot Drinks', 'Hot Drinks'), ('Soft Drinks', 'Soft Drinks'), ('Sandwitches', 'Sandwitches'), ('Printer', 'Printer'), ('Meeting Room', 'Meeting Room'), ('Electricity Bill', 'Electricity Bill'), ('Internet Bill', 'Internet Bill')], db_index=True, max_length=100)),
                ('exposure', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TofaProductsRepository',
            fields=[
                ('item_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('item_description', models.CharField(max_length=1000)),
                ('item_quantity', models.BigIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchers_app.categorization')),
            ],
        ),
        migrations.CreateModel(
            name='TofaProductsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INCart_Pending', 'INCart_Pending'), ('INPreparation', 'INPreparation'), ('Served', 'Served'), ('PAID_Closed', 'PAID_Closed')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchers_app.tofaproductsrepository')),
            ],
        ),
        migrations.CreateModel(
            name='TofaProductsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('transaction_Direction', models.CharField(choices=[('TOFA_Sell', 'TOFA_Sell'), ('TOFA_Buy', 'TOFA_Buy')], db_index=True, max_length=20)),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchers_app.tofaproductsrepository')),
            ],
        ),
    ]
