# Generated by Django 5.2.4 on 2025-07-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='categorization',
            constraint=models.UniqueConstraint(fields=('main_category', 'sub_category'), name='unique_main_sub'),
        ),
    ]
