# Generated by Django 5.2.4 on 2025-07-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers_app', '0002_categorization_unique_main_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='tofaproductsrepository',
            name='brand',
            field=models.CharField(default='hi', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tofaproductsrepository',
            name='price',
            field=models.FloatField(default=1.0, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='tofaproductsrepository',
            constraint=models.UniqueConstraint(fields=('item_name', 'category', 'brand'), name='product_uniqueness'),
        ),
    ]
