# Generated by Django 5.2.4 on 2025-07-16 22:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers_app', '0003_tofaproductsrepository_brand_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tofaproductsorder',
            name='table_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tofaproductsrepository',
            name='price',
            field=models.FloatField(max_length=1000),
        ),
        migrations.AddConstraint(
            model_name='tofaproductsorder',
            constraint=models.UniqueConstraint(fields=('item_name', 'user'), name='unique_item_incart'),
        ),
    ]
