# Generated by Django 5.2.4 on 2025-07-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers_app', '0005_alter_tofaproductsorder_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tofaproductsorder',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
