# Generated by Django 5.2.4 on 2025-07-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers_app', '0006_tofaproductsorder_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tofaproductsorder',
            name='fullfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
