# Generated by Django 5.2.4 on 2025-07-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers_app', '0007_tofaproductsorder_fullfilled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tofaproductsorder',
            name='order_number',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tofaproductsorder',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
