# Generated by Django 5.2.4 on 2025-07-17 21:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers_app', '0008_tofaproductsorder_order_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tofaproductsorder',
            name='unique_item_incart',
        ),
        migrations.AddConstraint(
            model_name='tofaproductsorder',
            constraint=models.UniqueConstraint(fields=('item_name', 'user', 'status'), name='unique_item_incart'),
        ),
    ]
