# Generated by Django 5.2.4 on 2025-07-17 21:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers_app', '0009_remove_tofaproductsorder_unique_item_incart_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tofaproductsorder',
            name='unique_item_incart',
        ),
        migrations.AlterField(
            model_name='tofaproductsorder',
            name='order_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='tofaproductsorder',
            constraint=models.UniqueConstraint(fields=('item_name', 'user', 'status', 'order_number'), name='unique_item_incart'),
        ),
    ]
