# Generated by Django 5.2.4 on 2025-07-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers_app', '0010_remove_tofaproductsorder_unique_item_incart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tofaproductsorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tofaproductsorder',
            name='status',
            field=models.CharField(choices=[('INCart_Pending', 'INCart_Pending'), ('INPreparation', 'INPreparation'), ('Served', 'Served'), ('PAID_Closed', 'PAID_Closed')], db_index=True, default='INCart_Pending', max_length=20),
        ),
    ]
