# Generated by Django 5.2.4 on 2025-07-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers_app', '0011_alter_tofaproductsorder_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tofaproductsorder',
            name='order_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
