# Generated by Django 5.2.4 on 2025-07-21 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchers_app', '0012_alter_tofaproductsorder_order_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tofaproductsorder',
            name='unique_item_incart',
        ),
    ]
