# Generated by Django 5.2.4 on 2025-07-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchers_app', '0014_tofaproductsorderid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tofaproductsorder',
            old_name='created_at',
            new_name='placed_in_cart_at',
        ),
    ]
