# Generated by Django 5.2.4 on 2025-07-24 22:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers_app', '0015_rename_created_at_tofaproductsorder_placed_in_cart_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tofaproductsorder',
            name='item_name',
            field=models.ForeignKey(on_delete=models.SET('Deleted'), to='watchers_app.tofaproductsrepository'),
        ),
        migrations.AlterField(
            model_name='tofaproductsorder',
            name='order_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('Deleted'), to='watchers_app.tofaproductsorderid'),
        ),
        migrations.AlterField(
            model_name='tofaproductsorder',
            name='user',
            field=models.ForeignKey(on_delete=models.SET('Deleted'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tofaproductsorderid',
            name='user',
            field=models.ForeignKey(on_delete=models.SET('Deleted'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tofaproductsrepository',
            name='category',
            field=models.ForeignKey(on_delete=models.SET('Deleted'), to='watchers_app.categorization'),
        ),
        migrations.CreateModel(
            name='bill_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_value', models.BigIntegerField(default=0)),
                ('bill_user', models.ForeignKey(on_delete=models.SET('Deleted'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
