# Generated by Django 5.2.4 on 2025-07-24 22:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers_app', '0016_alter_tofaproductsorder_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_id',
            name='bill_issue_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
