# Generated by Django 5.2.4 on 2025-07-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers_app', '0017_bill_id_bill_issue_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_id',
            name='bill_closure_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bill_id',
            name='bill_status',
            field=models.CharField(choices=[('CUSTOMER_REQUEST_TO_CLOSE', 'CUSTOMER_REQUEST_TO_CLOSE'), ('SETTELLED', 'SETTELLED')], default='CUSTOMER_REQUEST_TO_CLOSE'),
        ),
    ]
