# Generated by Django 5.2.4 on 2025-07-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers_app', '0018_bill_id_bill_closure_time_bill_id_bill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tofaproductsorder',
            name='bill_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('Deleted'), to='watchers_app.bill_id'),
        ),
    ]
