# Generated by Django 5.2.4 on 2025-07-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers_app', '0019_tofaproductsorder_bill_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tofaproductsorder',
            name='status',
        ),
        migrations.AddField(
            model_name='tofaproductsorderid',
            name='status',
            field=models.CharField(choices=[('INPreparation', 'INPreparation'), ('Served', 'Served'), ('PAID_Closed', 'PAID_Closed')], db_index=True, default='INPreparation', max_length=20),
        ),
        migrations.AlterField(
            model_name='bill_id',
            name='bill_status',
            field=models.CharField(choices=[('CUSTOMER_REQUEST_TO_CLOSE', 'CUSTOMER_REQUEST_TO_CLOSE'), ('SETTELLED', 'SETTELLED'), ('RETURNED_TO_CUSTOMER', 'RETURNED_TO_CUSTOMER')], default='CUSTOMER_REQUEST_TO_CLOSE'),
        ),
    ]
