# Generated by Django 5.2.4 on 2025-07-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers_app', '0020_remove_tofaproductsorder_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tofaproductsorder',
            name='bill_number',
        ),
        migrations.RemoveField(
            model_name='tofaproductsorder',
            name='table_number',
        ),
        migrations.AddField(
            model_name='tofaproductsorderid',
            name='bill_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('Deleted'), to='watchers_app.bill_id'),
        ),
        migrations.AddField(
            model_name='tofaproductsorderid',
            name='table_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
