# Generated by Django 5.2.4 on 2025-07-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers_app', '0021_remove_tofaproductsorder_bill_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tofaproductsorder',
            name='fullfilled_at',
        ),
        migrations.AddField(
            model_name='tofaproductsorderid',
            name='fullfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
